# Generated by Django 5.1.2 on 2025-04-04 16:47

import django.db.models.deletion
import webshadeApp.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webshadeAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('holder_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(default='-', max_length=50)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('balance', models.IntegerField(default=0)),
                ('refer_by', models.CharField(blank=True, max_length=50)),
                ('commision', models.IntegerField(default=0)),
                ('last_login', models.CharField(blank=True, max_length=50)),
                ('telegram_reward', models.BooleanField(default=False)),
                ('telegram_group_reward', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='withdrawal_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('with_id', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(default='Processing', max_length=50)),
                ('holder_name', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='whatsappConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(default=webshadeApp.functions.get_time_string, max_length=50)),
                ('onlineTime', models.IntegerField(default=0)),
                ('commission', models.IntegerField(default=0)),
                ('status', models.CharField(default='Processing', max_length=50)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('remark', models.CharField(blank=True, max_length=50)),
                ('admin_id', models.CharField(blank=True, max_length=50)),
                ('upper_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='webshadeAdmin.requesthandlingadmin')),
            ],
        ),
    ]
