# Generated by Django 5.1.2 on 2025-01-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('holder_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(default='-', max_length=50)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('balance', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, default='logged', max_length=50)),
                ('whatsapp_code', models.CharField(blank=True, max_length=50)),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('refer_by', models.CharField(blank=True, max_length=50)),
                ('commision', models.IntegerField(default=0)),
                ('stay_time', models.CharField(default='0', max_length=50)),
                ('by_whom', models.CharField(default='self', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='withdrawal_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_id', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(default='Processing', max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
    ]
