# Generated by Django 5.1.2 on 2025-03-06 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('holder_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(default='-', max_length=50)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('balance', models.IntegerField(default=0)),
                ('refer_by', models.CharField(blank=True, max_length=50)),
                ('commision', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='whatsappConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('onlineTime', models.IntegerField(default=0)),
                ('commission', models.IntegerField(default=0)),
                ('status', models.CharField(default='Processing', max_length=50)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('successTimestamp', models.CharField(default='0', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='withdrawal_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('with_id', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(default='Processing', max_length=50)),
                ('holder_name', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
    ]
