# Generated by Django 5.1.2 on 2025-01-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='account_locked',
            field=models.BooleanField(default=False),
        ),
    ]
