# Generated by Django 5.1.2 on 2025-03-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconnection',
            name='remark',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
