# Generated by Django 5.1.2 on 2025-01-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0002_userdetail_account_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='whatsappConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('onlineTime', models.CharField(default='0', max_length=50)),
                ('cosmission', models.CharField(default='0', max_length=50)),
                ('status', models.CharField(default='Processing', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='by_whom',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='stay_time',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='whatsapp_code',
        ),
    ]
