# Generated by Django 5.1.2 on 2025-03-07 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0002_whatsappconnection_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappconnection',
            name='serial',
        ),
    ]
