# Generated by Django 5.1.2 on 2025-01-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0003_whatsappconnection_remove_userdetail_by_whom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='account_locked',
            new_name='active',
        ),
    ]
