# Generated by Django 5.1.2 on 2025-03-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0003_remove_whatsappconnection_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='active',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='last_login',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
