# Generated by Django 5.1.2 on 2025-01-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0004_rename_account_locked_userdetail_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsappconnection',
            old_name='cosmission',
            new_name='commission',
        ),
    ]
