# Generated by Django 5.1.2 on 2025-03-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0004_remove_userdetail_active_userdetail_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='telegram_reward',
            field=models.BooleanField(default=False),
        ),
    ]
