# Generated by Django 5.1.2 on 2025-01-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0005_rename_cosmission_whatsappconnection_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconnection',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
