# Generated by Django 5.1.2 on 2025-03-14 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0006_chromeinstance_userdetail_telegram_group_reward'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='chromeinstance',
        #     name='task_id',
        # ),
        migrations.AddField(
            model_name='chromeinstance',
            name='user_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappconnection',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='whatsappconnection',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
