# Generated by Django 5.1.2 on 2025-01-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0006_whatsappconnection_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconnection',
            name='successTimestamp',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
