# Generated by Django 5.1.2 on 2025-03-14 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0007_remove_chromeinstance_task_id_chromeinstance_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappconnection',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
