# Generated by Django 5.1.2 on 2025-02-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0007_whatsappconnection_successtimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal_request',
            name='ifsc',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
