# Generated by Django 5.1.2 on 2025-03-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0008_alter_whatsappconnection_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChromeInstance',
        ),
        migrations.AddField(
            model_name='whatsappconnection',
            name='admin_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
