# Generated by Django 5.1.2 on 2025-02-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0008_withdrawal_request_ifsc'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal_request',
            name='holder_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
