# Generated by Django 5.1.2 on 2025-02-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0009_withdrawal_request_holder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappconnection',
            name='onlineTime',
            field=models.IntegerField(default=0),
        ),
    ]
