# Generated by Django 5.1.2 on 2025-02-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0010_alter_whatsappconnection_onlinetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappconnection',
            name='commission',
            field=models.IntegerField(default=0),
        ),
    ]
