# Generated by Django 5.1.2 on 2025-03-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0010_chromeinstance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChromeInstance',
        ),
    ]
