# Generated by Django 5.1.2 on 2025-03-16 23:03

import webshadeApp.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0011_delete_chromeinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappconnection',
            name='created_at',
            field=models.DateTimeField(default=webshadeApp.functions.get_time_string),
        ),
        migrations.AlterField(
            model_name='whatsappconnection',
            name='time',
            field=models.TimeField(default=webshadeApp.functions.get_time_string),
        ),
    ]
