# Generated by Django 5.1.2 on 2025-02-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0011_alter_whatsappconnection_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal_request',
            name='user_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
