# Generated by Django 5.1.2 on 2025-02-27 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0012_withdrawal_request_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal_request',
            name='phone',
        ),
    ]
