# Generated by Django 5.1.2 on 2025-03-17 21:24

import webshadeApp.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0012_alter_whatsappconnection_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappconnection',
            name='created_at',
            field=models.CharField(default=webshadeApp.functions.get_time_string, max_length=50),
        ),
    ]
