# Generated by Django 5.1.2 on 2025-03-18 11:10

import webshadeApp.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeApp', '0013_alter_whatsappconnection_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappconnection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='whatsappconnection',
            name='successTimestamp',
        ),
        migrations.AlterField(
            model_name='whatsappconnection',
            name='time',
            field=models.CharField(default=webshadeApp.functions.get_time_string, max_length=50),
        ),
    ]
