# Generated by Django 5.1.2 on 2025-03-18 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeAdmin', '0006_remove_requesthandlingadmin_active_task'),
        ('webshadeApp', '0014_remove_whatsappconnection_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconnection',
            name='upper_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='webshadeAdmin.requesthandlingadmin'),
        ),
    ]
