# Generated by Django 5.1.2 on 2025-04-04 16:47

import webshadeAdmin.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('login_by', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(default='no login', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequestHandlingAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chat_id', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('workon', models.CharField(max_length=50)),
                ('admin_id', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('special_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='revenueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(blank=True, max_length=50)),
                ('revenue_id', models.CharField(max_length=50)),
                ('admin_id', models.CharField(max_length=50)),
                ('admin_name', models.CharField(max_length=50)),
                ('last_balance', models.IntegerField(default=0)),
                ('withdrawal_amount', models.IntegerField(default=0)),
                ('date', models.CharField(default=webshadeAdmin.functions.get_date_string, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='reward_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_24', models.IntegerField(default=50)),
                ('amount_48', models.IntegerField(default=30)),
                ('amount_72', models.IntegerField(default=20)),
                ('amount_96', models.IntegerField(default=10)),
                ('amount_120', models.IntegerField(default=10)),
                ('amount_144', models.IntegerField(default=10)),
                ('amount_168', models.IntegerField(default=10)),
                ('server_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='whatsappPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_id', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('releaser', models.CharField(max_length=50)),
                ('date', models.CharField(default=webshadeAdmin.functions.get_date_string, max_length=50)),
                ('time', models.CharField(default=webshadeAdmin.functions.get_time_string, max_length=50)),
            ],
        ),
    ]
