# Generated by Django 5.1.2 on 2025-02-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward_price',
            name='amount_72_plus',
        ),
        migrations.AddField(
            model_name='reward_price',
            name='amount_120',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='reward_price',
            name='amount_144',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='reward_price',
            name='amount_168',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='reward_price',
            name='amount_96',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='reward_price',
            name='amount_24',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='reward_price',
            name='amount_48',
            field=models.IntegerField(default=30),
        ),
    ]
