# Generated by Django 5.1.2 on 2025-03-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHandlingAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chat_id', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('admin_id', models.CharField(max_length=50)),
            ],
        ),
    ]
