# Generated by Django 5.1.2 on 2025-03-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeAdmin', '0002_requesthandlingadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthandlingadmin',
            name='active_task',
            field=models.IntegerField(default=0),
        ),
    ]
