# Generated by Django 5.1.2 on 2025-03-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeAdmin', '0004_whatsapppayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthandlingadmin',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
