# Generated by Django 5.1.2 on 2025-03-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeAdmin', '0006_remove_requesthandlingadmin_active_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthandlingadmin',
            name='workon',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
