# Generated by Django 5.1.2 on 2025-03-21 14:08

import webshadeAdmin.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeAdmin', '0007_requesthandlingadmin_workon'),
    ]

    operations = [
        migrations.CreateModel(
            name='revenueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_id', models.CharField(max_length=50)),
                ('admin_id', models.CharField(max_length=50)),
                ('admin_name', models.CharField(max_length=50)),
                ('last_balance', models.IntegerField(default=0)),
                ('withdrawal_amount', models.IntegerField(default=0)),
                ('date', models.CharField(default=webshadeAdmin.functions.get_date_string, max_length=50)),
            ],
        ),
    ]
