# Generated by Django 5.1.2 on 2025-03-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeAdmin', '0008_revenuerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuerecord',
            name='special_staff',
            field=models.BooleanField(default=False),
        ),
    ]
