# Generated by Django 5.1.2 on 2025-03-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeAdmin', '0009_revenuerecord_special_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenuerecord',
            name='special_staff',
        ),
        migrations.AddField(
            model_name='requesthandlingadmin',
            name='special_staff',
            field=models.BooleanField(default=False),
        ),
    ]
