# Generated by Django 5.1.2 on 2025-03-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshadeAdmin', '0010_remove_revenuerecord_special_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuerecord',
            name='record_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
